# Generated by Django 3.1.4 on 2022-07-11 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('bucket', models.IntegerField(choices=[(1, '1 Day'), (2, '3 Day'), (3, '7 Day'), (4, '16 Day'), (5, '30 Day')], default=1)),
                ('next_review_at', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 21, 28, 29, 837915, tzinfo=utc))),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
